---

- name: Setup Debian specific variables (set_fact)
  set_fact:
    tor_user: debian-tor

- name: Ensure torproject gpg key is installed (A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89)
  sudo: yes
  apt_key: data="{{ lookup('file', 'deb.torproject.org_A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.pub') }}"
    id=A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state=present

- name: Ensure torproject.org repository is present (APT)
  sudo: yes
  apt_repository: repo='deb http://deb.torproject.org/torproject.org {{ tor_distribution_release }} main'
    state=present 
    update_cache=yes

# waiting for trac ticket #14997
#- name: Ensure  torproject.org alpha repo is present (if enabled)
#  apt_repository: >
#    repo='deb http://deb.torproject.org/torproject.org  main'
#    state=present 
#    update_cache=yes
#  when: tor_alpha is True

# we specifically opt for present over latest to improve performance
# "latest" is covered by auto updates
- name: Ensure Tor is installed (APT)
  sudo: yes
  apt: pkg="{{ item }}" state=present
  with_items: 
    - deb.torproject.org-keyring
    - tor
  # apt starts a tor client instance by default after installing the package
  # we do not need that
  notify:
    - stop tor
    - disable-sysv-debian tor

- name: Ensure the presence of the multi-instance systemd unit file (Debian)
  sudo: yes
  template: src=debian_tor@.service dest=/lib/systemd/system/tor@.service owner=root mode=0644 backup=yes
  when: ansible_distribution == 'Debian'
  notify: systemctl daemon-reload

- name: Ensure the presence of the multi-instance systemd unit file (Ubuntu)
  sudo: yes
  copy: src=ubuntu_tor@.service dest=/lib/systemd/system/tor@.service owner=root mode=0644 backup=yes
  when: ansible_distribution == 'Ubuntu'
  notify: systemctl daemon-reload

- name: Ensure AppArmor allows access to necessary files (Ubuntu)
  sudo: yes
  lineinfile: dest=/etc/apparmor.d/local/system_tor line={{ item }}
  with_items:
    - '/etc/tor/enabled/*\ r,'
    - '/{,var/}run/tor/*.pid\ w,'
    - '/var/lib/tor/**\ w,'
  when: ansible_distribution == 'Ubuntu'
  notify: restart apparmor

- meta: flush_handlers
