---

- name: Setup OpenBSD specific variables (set_fact)
  set_fact:
    tor_DataDir: /var/tor
    tor_ConfDir: /etc/tor/enabled
  tags:
   - reconfigure
   - renewkey
   - createdir

- name: Ensure Tor is installed (OpenBSD)
  become: yes
  openbsd_pkg: name=tor state=present

- name: Gather current system-wide file descriptor limits (OpenBSD)
  shell: "sysctl kern.maxfiles|cut -d= -f2"
  register: currentlimits

- name: Ensure system-wide runtime file descriptor limits are reasonable (OpenBSD)
  become: yes
  command: "sysctl kern.maxfiles=20000"
  when: currentlimits.stdout|int < 20000

- name: Ensure system-wide persistent file descriptor limits are reasonable (OpenBSD)
  become: yes
  lineinfile: dest=/etc/sysctl.conf regexp=^kern.maxfiles line="kern.maxfiles=20000" create=yes
  when: currentlimits.stdout|int < 20000

# We rise openfiles limits for every tor instance separately.
# An instance is identified by its rc.d file name.
- name: Ensure Tor process file descriptor limits are reasonable (OpenBSD)
  become: yes
  lineinfile: "dest=/etc/login.conf line='tor{{ item[0]| replace('.','_') }}_{{ item.1.orport }}::openfiles-max=13500::tc=daemon:'"
  with_nested:
   - tor_ips
   - tor_ports
  #TODO
  #notify: restart tor
